# kube.zsh — per-directory kube context routing.
#
# Directory → KUBECONFIG binding:
#   ExampleOrg trees -> KUBECONFIG=~/.kube/config (where workctl writes
#                        enterprise creds; current-context left exactly as
#                        workctl set it — no auto-selection of a cluster).
#   everywhere else   -> KUBECONFIG points at a standalone homelab kubeconfig
#                        whose current-context is admin@homelab.
#
# Env-based ONLY, same `case "$PWD" in */ExampleOrg/*)` cwd test as ai.zsh:
#   - no `kubie ctx` on cd — kubie is subshell-based and auto-entering it from
#     a chpwd hook would nest/recurse. kubie stays the tool for EXPLICIT
#     ad-hoc switches on top of this default binding.
#   - no mutation of ~/.kube/config (that file stays workctl's source of truth).
#   - not a hard boundary: homelab stays reachable from a work dir (and
#     vice-versa) via an explicit `kubie ctx` — this is default-selection,
#     not access control.
#   - no workctl credential auto-refresh on cd; run workctl manually when
#     enterprise creds are stale.
#
# Inside a kubie subshell (KUBIE_ACTIVE=1) the hook backs off entirely so
# kubie's own scoped KUBECONFIG wins for the life of that subshell.

# _kube_homelab_config: echo the standalone homelab kubeconfig path.
# Preferred: ~/.kube/homelab.yaml — generated by install.sh via
#   kubectl config view --minify --flatten --context=admin@homelab
# Fallback: the homelab repo kubeconfig (note: on this machine that
# file is NOT standalone — it carries enterprise contexts too — but its
# current-context is admin@homelab, so the default still lands right).
_kube_homelab_config() {
  if [[ -f "$HOME/.kube/homelab.yaml" ]]; then
    print -r -- "$HOME/.kube/homelab.yaml"
  elif [[ -f "$HOME/go/src/github.com/sergeybataev/homelab/kubeconfig" ]]; then
    print -r -- "$HOME/go/src/github.com/sergeybataev/homelab/kubeconfig"
  fi
}

_kube_chpwd() {
  [[ -n "$KUBIE_ACTIVE" ]] && return
  case "$PWD" in
    */ExampleOrg/*)
      export KUBECONFIG="$HOME/.kube/config"
      ;;
    *)
      local homelab
      homelab="$(_kube_homelab_config)"
      if [[ -n "$homelab" ]]; then
        export KUBECONFIG="$homelab"
      else
        # no homelab kubeconfig anywhere — fall back to kubectl's default
        unset KUBECONFIG
      fi
      ;;
  esac
}

autoload -Uz add-zsh-hook
add-zsh-hook chpwd _kube_chpwd
_kube_chpwd
